<?php
/**
 * BFBordeModelsComandosOrganismosOrganismoDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * BFBordeModelsComandosOrganismosOrganismoDto Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsComandosOrganismosOrganismoDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BF.Borde.Models.Comandos.Organismos.OrganismoDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'codigo_organismo' => 'string',
'tipo' => 'string',
'nombre' => 'string',
'descripcion' => 'string',
'callback_service_url' => 'string',
'callback_auth_key' => 'string',
'provincia' => 'string',
'client_id' => 'string',
'normativa_convenio_tipo' => 'string',
'normativa_convenio_numero' => 'string',
'openid_endpoint' => 'string',
'datos_contacto' => '\Swagger\Client\Model\BFBordeModelsComandosOrganismosContactoDto[]',
'policies' => '\Swagger\Client\Model\BFBordeModelsComandosOrganismosPoliticaDto',
'timestamp_ultima_modificacion' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'codigo_organismo' => null,
'tipo' => null,
'nombre' => null,
'descripcion' => null,
'callback_service_url' => null,
'callback_auth_key' => null,
'provincia' => null,
'client_id' => null,
'normativa_convenio_tipo' => null,
'normativa_convenio_numero' => null,
'openid_endpoint' => null,
'datos_contacto' => null,
'policies' => null,
'timestamp_ultima_modificacion' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'codigo_organismo' => 'codigo_organismo',
'tipo' => 'tipo',
'nombre' => 'nombre',
'descripcion' => 'descripcion',
'callback_service_url' => 'callback_service_url',
'callback_auth_key' => 'callback_auth_key',
'provincia' => 'provincia',
'client_id' => 'clientId',
'normativa_convenio_tipo' => 'normativa_convenio_tipo',
'normativa_convenio_numero' => 'normativa_convenio_numero',
'openid_endpoint' => 'openid_endpoint',
'datos_contacto' => 'datos_contacto',
'policies' => 'policies',
'timestamp_ultima_modificacion' => 'timestamp_ultima_modificacion'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'codigo_organismo' => 'setCodigoOrganismo',
'tipo' => 'setTipo',
'nombre' => 'setNombre',
'descripcion' => 'setDescripcion',
'callback_service_url' => 'setCallbackServiceUrl',
'callback_auth_key' => 'setCallbackAuthKey',
'provincia' => 'setProvincia',
'client_id' => 'setClientId',
'normativa_convenio_tipo' => 'setNormativaConvenioTipo',
'normativa_convenio_numero' => 'setNormativaConvenioNumero',
'openid_endpoint' => 'setOpenidEndpoint',
'datos_contacto' => 'setDatosContacto',
'policies' => 'setPolicies',
'timestamp_ultima_modificacion' => 'setTimestampUltimaModificacion'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'codigo_organismo' => 'getCodigoOrganismo',
'tipo' => 'getTipo',
'nombre' => 'getNombre',
'descripcion' => 'getDescripcion',
'callback_service_url' => 'getCallbackServiceUrl',
'callback_auth_key' => 'getCallbackAuthKey',
'provincia' => 'getProvincia',
'client_id' => 'getClientId',
'normativa_convenio_tipo' => 'getNormativaConvenioTipo',
'normativa_convenio_numero' => 'getNormativaConvenioNumero',
'openid_endpoint' => 'getOpenidEndpoint',
'datos_contacto' => 'getDatosContacto',
'policies' => 'getPolicies',
'timestamp_ultima_modificacion' => 'getTimestampUltimaModificacion'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['codigo_organismo'] = isset($data['codigo_organismo']) ? $data['codigo_organismo'] : null;
        $this->container['tipo'] = isset($data['tipo']) ? $data['tipo'] : null;
        $this->container['nombre'] = isset($data['nombre']) ? $data['nombre'] : null;
        $this->container['descripcion'] = isset($data['descripcion']) ? $data['descripcion'] : null;
        $this->container['callback_service_url'] = isset($data['callback_service_url']) ? $data['callback_service_url'] : null;
        $this->container['callback_auth_key'] = isset($data['callback_auth_key']) ? $data['callback_auth_key'] : null;
        $this->container['provincia'] = isset($data['provincia']) ? $data['provincia'] : null;
        $this->container['client_id'] = isset($data['client_id']) ? $data['client_id'] : null;
        $this->container['normativa_convenio_tipo'] = isset($data['normativa_convenio_tipo']) ? $data['normativa_convenio_tipo'] : null;
        $this->container['normativa_convenio_numero'] = isset($data['normativa_convenio_numero']) ? $data['normativa_convenio_numero'] : null;
        $this->container['openid_endpoint'] = isset($data['openid_endpoint']) ? $data['openid_endpoint'] : null;
        $this->container['datos_contacto'] = isset($data['datos_contacto']) ? $data['datos_contacto'] : null;
        $this->container['policies'] = isset($data['policies']) ? $data['policies'] : null;
        $this->container['timestamp_ultima_modificacion'] = isset($data['timestamp_ultima_modificacion']) ? $data['timestamp_ultima_modificacion'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets codigo_organismo
     *
     * @return string
     */
    public function getCodigoOrganismo()
    {
        return $this->container['codigo_organismo'];
    }

    /**
     * Sets codigo_organismo
     *
     * @param string $codigo_organismo codigo_organismo
     *
     * @return $this
     */
    public function setCodigoOrganismo($codigo_organismo)
    {
        $this->container['codigo_organismo'] = $codigo_organismo;

        return $this;
    }

    /**
     * Gets tipo
     *
     * @return string
     */
    public function getTipo()
    {
        return $this->container['tipo'];
    }

    /**
     * Sets tipo
     *
     * @param string $tipo tipo
     *
     * @return $this
     */
    public function setTipo($tipo)
    {
        $this->container['tipo'] = $tipo;

        return $this;
    }

    /**
     * Gets nombre
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->container['nombre'];
    }

    /**
     * Sets nombre
     *
     * @param string $nombre nombre
     *
     * @return $this
     */
    public function setNombre($nombre)
    {
        $this->container['nombre'] = $nombre;

        return $this;
    }

    /**
     * Gets descripcion
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->container['descripcion'];
    }

    /**
     * Sets descripcion
     *
     * @param string $descripcion descripcion
     *
     * @return $this
     */
    public function setDescripcion($descripcion)
    {
        $this->container['descripcion'] = $descripcion;

        return $this;
    }

    /**
     * Gets callback_service_url
     *
     * @return string
     */
    public function getCallbackServiceUrl()
    {
        return $this->container['callback_service_url'];
    }

    /**
     * Sets callback_service_url
     *
     * @param string $callback_service_url callback_service_url
     *
     * @return $this
     */
    public function setCallbackServiceUrl($callback_service_url)
    {
        $this->container['callback_service_url'] = $callback_service_url;

        return $this;
    }

    /**
     * Gets callback_auth_key
     *
     * @return string
     */
    public function getCallbackAuthKey()
    {
        return $this->container['callback_auth_key'];
    }

    /**
     * Sets callback_auth_key
     *
     * @param string $callback_auth_key callback_auth_key
     *
     * @return $this
     */
    public function setCallbackAuthKey($callback_auth_key)
    {
        $this->container['callback_auth_key'] = $callback_auth_key;

        return $this;
    }

    /**
     * Gets provincia
     *
     * @return string
     */
    public function getProvincia()
    {
        return $this->container['provincia'];
    }

    /**
     * Sets provincia
     *
     * @param string $provincia provincia
     *
     * @return $this
     */
    public function setProvincia($provincia)
    {
        $this->container['provincia'] = $provincia;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string $client_id client_id
     *
     * @return $this
     */
    public function setClientId($client_id)
    {
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets normativa_convenio_tipo
     *
     * @return string
     */
    public function getNormativaConvenioTipo()
    {
        return $this->container['normativa_convenio_tipo'];
    }

    /**
     * Sets normativa_convenio_tipo
     *
     * @param string $normativa_convenio_tipo normativa_convenio_tipo
     *
     * @return $this
     */
    public function setNormativaConvenioTipo($normativa_convenio_tipo)
    {
        $this->container['normativa_convenio_tipo'] = $normativa_convenio_tipo;

        return $this;
    }

    /**
     * Gets normativa_convenio_numero
     *
     * @return string
     */
    public function getNormativaConvenioNumero()
    {
        return $this->container['normativa_convenio_numero'];
    }

    /**
     * Sets normativa_convenio_numero
     *
     * @param string $normativa_convenio_numero normativa_convenio_numero
     *
     * @return $this
     */
    public function setNormativaConvenioNumero($normativa_convenio_numero)
    {
        $this->container['normativa_convenio_numero'] = $normativa_convenio_numero;

        return $this;
    }

    /**
     * Gets openid_endpoint
     *
     * @return string
     */
    public function getOpenidEndpoint()
    {
        return $this->container['openid_endpoint'];
    }

    /**
     * Sets openid_endpoint
     *
     * @param string $openid_endpoint openid_endpoint
     *
     * @return $this
     */
    public function setOpenidEndpoint($openid_endpoint)
    {
        $this->container['openid_endpoint'] = $openid_endpoint;

        return $this;
    }

    /**
     * Gets datos_contacto
     *
     * @return \Swagger\Client\Model\BFBordeModelsComandosOrganismosContactoDto[]
     */
    public function getDatosContacto()
    {
        return $this->container['datos_contacto'];
    }

    /**
     * Sets datos_contacto
     *
     * @param \Swagger\Client\Model\BFBordeModelsComandosOrganismosContactoDto[] $datos_contacto datos_contacto
     *
     * @return $this
     */
    public function setDatosContacto($datos_contacto)
    {
        $this->container['datos_contacto'] = $datos_contacto;

        return $this;
    }

    /**
     * Gets policies
     *
     * @return \Swagger\Client\Model\BFBordeModelsComandosOrganismosPoliticaDto
     */
    public function getPolicies()
    {
        return $this->container['policies'];
    }

    /**
     * Sets policies
     *
     * @param \Swagger\Client\Model\BFBordeModelsComandosOrganismosPoliticaDto $policies policies
     *
     * @return $this
     */
    public function setPolicies($policies)
    {
        $this->container['policies'] = $policies;

        return $this;
    }

    /**
     * Gets timestamp_ultima_modificacion
     *
     * @return string
     */
    public function getTimestampUltimaModificacion()
    {
        return $this->container['timestamp_ultima_modificacion'];
    }

    /**
     * Sets timestamp_ultima_modificacion
     *
     * @param string $timestamp_ultima_modificacion timestamp_ultima_modificacion
     *
     * @return $this
     */
    public function setTimestampUltimaModificacion($timestamp_ultima_modificacion)
    {
        $this->container['timestamp_ultima_modificacion'] = $timestamp_ultima_modificacion;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
