<?php
/**
 * BFBordeModelsServicesCausasBuscarCausaResponseItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * BFBordeModelsServicesCausasBuscarCausaResponseItem Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsServicesCausasBuscarCausaResponseItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BF.Borde.Models.Services.Causas.BuscarCausaResponse+Item';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'codigo_organismo' => 'string',
'codigo_dependencia' => 'string',
'nro_causa' => 'string',
'caratula' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'codigo_organismo' => null,
'codigo_dependencia' => null,
'nro_causa' => null,
'caratula' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'codigo_organismo' => 'codigo_organismo',
'codigo_dependencia' => 'codigo_dependencia',
'nro_causa' => 'nro_causa',
'caratula' => 'caratula'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'codigo_organismo' => 'setCodigoOrganismo',
'codigo_dependencia' => 'setCodigoDependencia',
'nro_causa' => 'setNroCausa',
'caratula' => 'setCaratula'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'codigo_organismo' => 'getCodigoOrganismo',
'codigo_dependencia' => 'getCodigoDependencia',
'nro_causa' => 'getNroCausa',
'caratula' => 'getCaratula'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['codigo_organismo'] = isset($data['codigo_organismo']) ? $data['codigo_organismo'] : null;
        $this->container['codigo_dependencia'] = isset($data['codigo_dependencia']) ? $data['codigo_dependencia'] : null;
        $this->container['nro_causa'] = isset($data['nro_causa']) ? $data['nro_causa'] : null;
        $this->container['caratula'] = isset($data['caratula']) ? $data['caratula'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets codigo_organismo
     *
     * @return string
     */
    public function getCodigoOrganismo()
    {
        return $this->container['codigo_organismo'];
    }

    /**
     * Sets codigo_organismo
     *
     * @param string $codigo_organismo codigo_organismo
     *
     * @return $this
     */
    public function setCodigoOrganismo($codigo_organismo)
    {
        $this->container['codigo_organismo'] = $codigo_organismo;

        return $this;
    }

    /**
     * Gets codigo_dependencia
     *
     * @return string
     */
    public function getCodigoDependencia()
    {
        return $this->container['codigo_dependencia'];
    }

    /**
     * Sets codigo_dependencia
     *
     * @param string $codigo_dependencia codigo_dependencia
     *
     * @return $this
     */
    public function setCodigoDependencia($codigo_dependencia)
    {
        $this->container['codigo_dependencia'] = $codigo_dependencia;

        return $this;
    }

    /**
     * Gets nro_causa
     *
     * @return string
     */
    public function getNroCausa()
    {
        return $this->container['nro_causa'];
    }

    /**
     * Sets nro_causa
     *
     * @param string $nro_causa nro_causa
     *
     * @return $this
     */
    public function setNroCausa($nro_causa)
    {
        $this->container['nro_causa'] = $nro_causa;

        return $this;
    }

    /**
     * Gets caratula
     *
     * @return string
     */
    public function getCaratula()
    {
        return $this->container['caratula'];
    }

    /**
     * Sets caratula
     *
     * @param string $caratula caratula
     *
     * @return $this
     */
    public function setCaratula($caratula)
    {
        $this->container['caratula'] = $caratula;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
