<?php
/**
 * BFBordeModelsSharedDtosDocumentoDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * BFBordeModelsSharedDtosDocumentoDto Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsSharedDtosDocumentoDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BF.Borde.Models.Shared.Dtos.DocumentoDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'payload_base64' => 'string',
'nombre_documento' => 'string',
'tipo_documento' => 'string',
'sha_256_payload' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'payload_base64' => null,
'nombre_documento' => null,
'tipo_documento' => null,
'sha_256_payload' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payload_base64' => 'payload_base64',
'nombre_documento' => 'nombre_documento',
'tipo_documento' => 'tipo_documento',
'sha_256_payload' => 'sha_256_payload'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payload_base64' => 'setPayloadBase64',
'nombre_documento' => 'setNombreDocumento',
'tipo_documento' => 'setTipoDocumento',
'sha_256_payload' => 'setSha256Payload'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payload_base64' => 'getPayloadBase64',
'nombre_documento' => 'getNombreDocumento',
'tipo_documento' => 'getTipoDocumento',
'sha_256_payload' => 'getSha256Payload'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['payload_base64'] = isset($data['payload_base64']) ? $data['payload_base64'] : null;
        $this->container['nombre_documento'] = isset($data['nombre_documento']) ? $data['nombre_documento'] : null;
        $this->container['tipo_documento'] = isset($data['tipo_documento']) ? $data['tipo_documento'] : null;
        $this->container['sha_256_payload'] = isset($data['sha_256_payload']) ? $data['sha_256_payload'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payload_base64
     *
     * @return string
     */
    public function getPayloadBase64()
    {
        return $this->container['payload_base64'];
    }

    /**
     * Sets payload_base64
     *
     * @param string $payload_base64 payload_base64
     *
     * @return $this
     */
    public function setPayloadBase64($payload_base64)
    {
        $this->container['payload_base64'] = $payload_base64;

        return $this;
    }

    /**
     * Gets nombre_documento
     *
     * @return string
     */
    public function getNombreDocumento()
    {
        return $this->container['nombre_documento'];
    }

    /**
     * Sets nombre_documento
     *
     * @param string $nombre_documento nombre_documento
     *
     * @return $this
     */
    public function setNombreDocumento($nombre_documento)
    {
        $this->container['nombre_documento'] = $nombre_documento;

        return $this;
    }

    /**
     * Gets tipo_documento
     *
     * @return string
     */
    public function getTipoDocumento()
    {
        return $this->container['tipo_documento'];
    }

    /**
     * Sets tipo_documento
     *
     * @param string $tipo_documento tipo_documento
     *
     * @return $this
     */
    public function setTipoDocumento($tipo_documento)
    {
        $this->container['tipo_documento'] = $tipo_documento;

        return $this;
    }

    /**
     * Gets sha_256_payload
     *
     * @return string
     */
    public function getSha256Payload()
    {
        return $this->container['sha_256_payload'];
    }

    /**
     * Sets sha_256_payload
     *
     * @param string $sha_256_payload sha_256_payload
     *
     * @return $this
     */
    public function setSha256Payload($sha_256_payload)
    {
        $this->container['sha_256_payload'] = $sha_256_payload;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
