<?php
/**
 * DocumentoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DocumentoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for brokerEnviarDocumentoPost
     *
     * .
     *
     */
    public function testBrokerEnviarDocumentoPost()
    {
    }

    /**
     * Test case for documentoBinarioGet
     *
     * .
     *
     */
    public function testDocumentoBinarioGet()
    {
    }

    /**
     * Test case for documentoDataGet
     *
     * .
     *
     */
    public function testDocumentoDataGet()
    {
    }

    /**
     * Test case for documentoGet
     *
     * .
     *
     */
    public function testDocumentoGet()
    {
    }

    /**
     * Test case for documentoLinkGet
     *
     * .
     *
     */
    public function testDocumentoLinkGet()
    {
    }

    /**
     * Test case for enviarPost
     *
     * .
     *
     */
    public function testEnviarPost()
    {
    }
}
