<?php
/**
 * DependenciasApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * DependenciasApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DependenciasApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation dependenciasDelete
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaEliminarRequest $body body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaEliminarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull
     */
    public function dependenciasDelete($body = null)
    {
        list($response) = $this->dependenciasDeleteWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation dependenciasDeleteWithHttpInfo
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaEliminarRequest $body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaEliminarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull, HTTP status code, HTTP response headers (array of strings)
     */
    public function dependenciasDeleteWithHttpInfo($body = null)
    {
        $returnType = '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaEliminarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull';
        $request = $this->dependenciasDeleteRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaEliminarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation dependenciasDeleteAsync
     *
     * 
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaEliminarRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function dependenciasDeleteAsync($body = null)
    {
        return $this->dependenciasDeleteAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation dependenciasDeleteAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaEliminarRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function dependenciasDeleteAsyncWithHttpInfo($body = null)
    {
        $returnType = '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaEliminarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull';
        $request = $this->dependenciasDeleteRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'dependenciasDelete'
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaEliminarRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function dependenciasDeleteRequest($body = null)
    {

        $resourcePath = '/dependencias';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation dependenciasGet
     *
     * @param  string $codigo_organismo codigo_organismo (optional)
     * @param  string $codigo_dependencia codigo_dependencia (optional)
     * @param  string $nombre_organismo nombre_organismo (optional)
     * @param  string $nombre nombre (optional)
     * @param  string $fuero fuero (optional)
     * @param  string $instancia instancia (optional)
     * @param  string $ciudad ciudad (optional)
     * @param  int $numero_pagina numero_pagina (optional)
     * @param  int $registros_por_pagina registros_por_pagina (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaBuscarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull
     */
    public function dependenciasGet($codigo_organismo = null, $codigo_dependencia = null, $nombre_organismo = null, $nombre = null, $fuero = null, $instancia = null, $ciudad = null, $numero_pagina = null, $registros_por_pagina = null)
    {
        list($response) = $this->dependenciasGetWithHttpInfo($codigo_organismo, $codigo_dependencia, $nombre_organismo, $nombre, $fuero, $instancia, $ciudad, $numero_pagina, $registros_por_pagina);
        return $response;
    }

    /**
     * Operation dependenciasGetWithHttpInfo
     *
     * @param  string $codigo_organismo (optional)
     * @param  string $codigo_dependencia (optional)
     * @param  string $nombre_organismo (optional)
     * @param  string $nombre (optional)
     * @param  string $fuero (optional)
     * @param  string $instancia (optional)
     * @param  string $ciudad (optional)
     * @param  int $numero_pagina (optional)
     * @param  int $registros_por_pagina (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaBuscarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull, HTTP status code, HTTP response headers (array of strings)
     */
    public function dependenciasGetWithHttpInfo($codigo_organismo = null, $codigo_dependencia = null, $nombre_organismo = null, $nombre = null, $fuero = null, $instancia = null, $ciudad = null, $numero_pagina = null, $registros_por_pagina = null)
    {
        $returnType = '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaBuscarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull';
        $request = $this->dependenciasGetRequest($codigo_organismo, $codigo_dependencia, $nombre_organismo, $nombre, $fuero, $instancia, $ciudad, $numero_pagina, $registros_por_pagina);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaBuscarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation dependenciasGetAsync
     *
     * 
     *
     * @param  string $codigo_organismo (optional)
     * @param  string $codigo_dependencia (optional)
     * @param  string $nombre_organismo (optional)
     * @param  string $nombre (optional)
     * @param  string $fuero (optional)
     * @param  string $instancia (optional)
     * @param  string $ciudad (optional)
     * @param  int $numero_pagina (optional)
     * @param  int $registros_por_pagina (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function dependenciasGetAsync($codigo_organismo = null, $codigo_dependencia = null, $nombre_organismo = null, $nombre = null, $fuero = null, $instancia = null, $ciudad = null, $numero_pagina = null, $registros_por_pagina = null)
    {
        return $this->dependenciasGetAsyncWithHttpInfo($codigo_organismo, $codigo_dependencia, $nombre_organismo, $nombre, $fuero, $instancia, $ciudad, $numero_pagina, $registros_por_pagina)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation dependenciasGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $codigo_organismo (optional)
     * @param  string $codigo_dependencia (optional)
     * @param  string $nombre_organismo (optional)
     * @param  string $nombre (optional)
     * @param  string $fuero (optional)
     * @param  string $instancia (optional)
     * @param  string $ciudad (optional)
     * @param  int $numero_pagina (optional)
     * @param  int $registros_por_pagina (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function dependenciasGetAsyncWithHttpInfo($codigo_organismo = null, $codigo_dependencia = null, $nombre_organismo = null, $nombre = null, $fuero = null, $instancia = null, $ciudad = null, $numero_pagina = null, $registros_por_pagina = null)
    {
        $returnType = '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaBuscarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull';
        $request = $this->dependenciasGetRequest($codigo_organismo, $codigo_dependencia, $nombre_organismo, $nombre, $fuero, $instancia, $ciudad, $numero_pagina, $registros_por_pagina);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'dependenciasGet'
     *
     * @param  string $codigo_organismo (optional)
     * @param  string $codigo_dependencia (optional)
     * @param  string $nombre_organismo (optional)
     * @param  string $nombre (optional)
     * @param  string $fuero (optional)
     * @param  string $instancia (optional)
     * @param  string $ciudad (optional)
     * @param  int $numero_pagina (optional)
     * @param  int $registros_por_pagina (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function dependenciasGetRequest($codigo_organismo = null, $codigo_dependencia = null, $nombre_organismo = null, $nombre = null, $fuero = null, $instancia = null, $ciudad = null, $numero_pagina = null, $registros_por_pagina = null)
    {

        $resourcePath = '/dependencias';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($codigo_organismo !== null) {
            $queryParams['codigo_organismo'] = ObjectSerializer::toQueryValue($codigo_organismo, null);
        }
        // query params
        if ($codigo_dependencia !== null) {
            $queryParams['codigo_dependencia'] = ObjectSerializer::toQueryValue($codigo_dependencia, null);
        }
        // query params
        if ($nombre_organismo !== null) {
            $queryParams['NombreOrganismo'] = ObjectSerializer::toQueryValue($nombre_organismo, null);
        }
        // query params
        if ($nombre !== null) {
            $queryParams['Nombre'] = ObjectSerializer::toQueryValue($nombre, null);
        }
        // query params
        if ($fuero !== null) {
            $queryParams['Fuero'] = ObjectSerializer::toQueryValue($fuero, null);
        }
        // query params
        if ($instancia !== null) {
            $queryParams['Instancia'] = ObjectSerializer::toQueryValue($instancia, null);
        }
        // query params
        if ($ciudad !== null) {
            $queryParams['Ciudad'] = ObjectSerializer::toQueryValue($ciudad, null);
        }
        // query params
        if ($numero_pagina !== null) {
            $queryParams['NumeroPagina'] = ObjectSerializer::toQueryValue($numero_pagina, 'int32');
        }
        // query params
        if ($registros_por_pagina !== null) {
            $queryParams['RegistrosPorPagina'] = ObjectSerializer::toQueryValue($registros_por_pagina, 'int32');
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation dependenciasPut
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaGuardarRequest $body body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaGuardarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull
     */
    public function dependenciasPut($body = null)
    {
        list($response) = $this->dependenciasPutWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation dependenciasPutWithHttpInfo
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaGuardarRequest $body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaGuardarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull, HTTP status code, HTTP response headers (array of strings)
     */
    public function dependenciasPutWithHttpInfo($body = null)
    {
        $returnType = '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaGuardarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull';
        $request = $this->dependenciasPutRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaGuardarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation dependenciasPutAsync
     *
     * 
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaGuardarRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function dependenciasPutAsync($body = null)
    {
        return $this->dependenciasPutAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation dependenciasPutAsyncWithHttpInfo
     *
     * 
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaGuardarRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function dependenciasPutAsyncWithHttpInfo($body = null)
    {
        $returnType = '\Swagger\Client\Model\BFCommonServiceResponse1BFBordeModelsServicesDependenciasDependenciaGuardarResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull';
        $request = $this->dependenciasPutRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'dependenciasPut'
     *
     * @param  \Swagger\Client\Model\BFBordeModelsApiModelDependenciaGuardarRequest $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function dependenciasPutRequest($body = null)
    {

        $resourcePath = '/dependencias';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain', 'application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain', 'application/json', 'text/json'],
                ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
