<?php
/**
 * BFBordeModelsSharedDtosCausaDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFBordeModelsSharedDtosCausaDtoTest Class Doc Comment
 *
 * @category    Class
 * @description BFBordeModelsSharedDtosCausaDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsSharedDtosCausaDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFBordeModelsSharedDtosCausaDto"
     */
    public function testBFBordeModelsSharedDtosCausaDto()
    {
    }

    /**
     * Test attribute "nro_causa"
     */
    public function testPropertyNroCausa()
    {
    }

    /**
     * Test attribute "caratula"
     */
    public function testPropertyCaratula()
    {
    }

    /**
     * Test attribute "dependencia"
     */
    public function testPropertyDependencia()
    {
    }
}
