<?php
/**
 * BFBordeModelsApiModelTicketBuscarRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFBordeModelsApiModelTicketBuscarRequestTest Class Doc Comment
 *
 * @category    Class
 * @description BFBordeModelsApiModelTicketBuscarRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsApiModelTicketBuscarRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFBordeModelsApiModelTicketBuscarRequest"
     */
    public function testBFBordeModelsApiModelTicketBuscarRequest()
    {
    }

    /**
     * Test attribute "uuid_respuesta"
     */
    public function testPropertyUuidRespuesta()
    {
    }

    /**
     * Test attribute "fecha_desde"
     */
    public function testPropertyFechaDesde()
    {
    }

    /**
     * Test attribute "fecha_hasta"
     */
    public function testPropertyFechaHasta()
    {
    }

    /**
     * Test attribute "origen"
     */
    public function testPropertyOrigen()
    {
    }

    /**
     * Test attribute "destino"
     */
    public function testPropertyDestino()
    {
    }

    /**
     * Test attribute "numero_pagina"
     */
    public function testPropertyNumeroPagina()
    {
    }

    /**
     * Test attribute "registros_por_pagina"
     */
    public function testPropertyRegistrosPorPagina()
    {
    }
}
