<?php
/**
 * BFBordeModelsComandosDependenciasDependenciaDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFBordeModelsComandosDependenciasDependenciaDtoTest Class Doc Comment
 *
 * @category    Class
 * @description BFBordeModelsComandosDependenciasDependenciaDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsComandosDependenciasDependenciaDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFBordeModelsComandosDependenciasDependenciaDto"
     */
    public function testBFBordeModelsComandosDependenciasDependenciaDto()
    {
    }

    /**
     * Test attribute "codigo_organismo"
     */
    public function testPropertyCodigoOrganismo()
    {
    }

    /**
     * Test attribute "codigo_dependencia"
     */
    public function testPropertyCodigoDependencia()
    {
    }

    /**
     * Test attribute "id_interno"
     */
    public function testPropertyIdInterno()
    {
    }

    /**
     * Test attribute "nombre"
     */
    public function testPropertyNombre()
    {
    }

    /**
     * Test attribute "descripcion"
     */
    public function testPropertyDescripcion()
    {
    }

    /**
     * Test attribute "fuero"
     */
    public function testPropertyFuero()
    {
    }

    /**
     * Test attribute "instancia"
     */
    public function testPropertyInstancia()
    {
    }

    /**
     * Test attribute "ubicacion"
     */
    public function testPropertyUbicacion()
    {
    }

    /**
     * Test attribute "datos_contacto"
     */
    public function testPropertyDatosContacto()
    {
    }
}
