<?php
/**
 * BFBordeModelsComandosDependenciasUbicacionDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFBordeModelsComandosDependenciasUbicacionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description BFBordeModelsComandosDependenciasUbicacionDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsComandosDependenciasUbicacionDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFBordeModelsComandosDependenciasUbicacionDto"
     */
    public function testBFBordeModelsComandosDependenciasUbicacionDto()
    {
    }

    /**
     * Test attribute "ciudad"
     */
    public function testPropertyCiudad()
    {
    }

    /**
     * Test attribute "calle"
     */
    public function testPropertyCalle()
    {
    }

    /**
     * Test attribute "numero"
     */
    public function testPropertyNumero()
    {
    }

    /**
     * Test attribute "piso_dpto"
     */
    public function testPropertyPisoDpto()
    {
    }

    /**
     * Test attribute "cp"
     */
    public function testPropertyCp()
    {
    }

    /**
     * Test attribute "nombre_agrup_geo"
     */
    public function testPropertyNombreAgrupGeo()
    {
    }

    /**
     * Test attribute "tipo_agrup_geo"
     */
    public function testPropertyTipoAgrupGeo()
    {
    }

    /**
     * Test attribute "georef"
     */
    public function testPropertyGeoref()
    {
    }
}
