<?php
/**
 * BFBordeModelsComandosEscribanoTicketDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFBordeModelsComandosEscribanoTicketDtoTest Class Doc Comment
 *
 * @category    Class
 * @description BFBordeModelsComandosEscribanoTicketDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsComandosEscribanoTicketDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFBordeModelsComandosEscribanoTicketDto"
     */
    public function testBFBordeModelsComandosEscribanoTicketDto()
    {
    }

    /**
     * Test attribute "id_reg_bfa"
     */
    public function testPropertyIdRegBfa()
    {
    }

    /**
     * Test attribute "hash_ticket"
     */
    public function testPropertyHashTicket()
    {
    }

    /**
     * Test attribute "ticket"
     */
    public function testPropertyTicket()
    {
    }

    /**
     * Test attribute "raw_data"
     */
    public function testPropertyRawData()
    {
    }

    /**
     * Test attribute "leido"
     */
    public function testPropertyLeido()
    {
    }
}
