<?php
/**
 * BFBordeModelsComandosOrganismosOrganismoDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFBordeModelsComandosOrganismosOrganismoDtoTest Class Doc Comment
 *
 * @category    Class
 * @description BFBordeModelsComandosOrganismosOrganismoDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFBordeModelsComandosOrganismosOrganismoDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFBordeModelsComandosOrganismosOrganismoDto"
     */
    public function testBFBordeModelsComandosOrganismosOrganismoDto()
    {
    }

    /**
     * Test attribute "codigo_organismo"
     */
    public function testPropertyCodigoOrganismo()
    {
    }

    /**
     * Test attribute "tipo"
     */
    public function testPropertyTipo()
    {
    }

    /**
     * Test attribute "nombre"
     */
    public function testPropertyNombre()
    {
    }

    /**
     * Test attribute "descripcion"
     */
    public function testPropertyDescripcion()
    {
    }

    /**
     * Test attribute "callback_service_url"
     */
    public function testPropertyCallbackServiceUrl()
    {
    }

    /**
     * Test attribute "callback_auth_key"
     */
    public function testPropertyCallbackAuthKey()
    {
    }

    /**
     * Test attribute "provincia"
     */
    public function testPropertyProvincia()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "normativa_convenio_tipo"
     */
    public function testPropertyNormativaConvenioTipo()
    {
    }

    /**
     * Test attribute "normativa_convenio_numero"
     */
    public function testPropertyNormativaConvenioNumero()
    {
    }

    /**
     * Test attribute "openid_endpoint"
     */
    public function testPropertyOpenidEndpoint()
    {
    }

    /**
     * Test attribute "datos_contacto"
     */
    public function testPropertyDatosContacto()
    {
    }

    /**
     * Test attribute "policies"
     */
    public function testPropertyPolicies()
    {
    }

    /**
     * Test attribute "timestamp_ultima_modificacion"
     */
    public function testPropertyTimestampUltimaModificacion()
    {
    }
}
