<?php
/**
 * BFCommonServiceResponse1BFBordeModelsServicesCausasBuscarCausaResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNullTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BF.Borde.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BFCommonServiceResponse1BFBordeModelsServicesCausasBuscarCausaResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNullTest Class Doc Comment
 *
 * @category    Class
 * @description BFCommonServiceResponse1BFBordeModelsServicesCausasBuscarCausaResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BFCommonServiceResponse1BFBordeModelsServicesCausasBuscarCausaResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNullTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BFCommonServiceResponse1BFBordeModelsServicesCausasBuscarCausaResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull"
     */
    public function testBFCommonServiceResponse1BFBordeModelsServicesCausasBuscarCausaResponseBFBordeModelsVersion11213CultureNeutralPublicKeyTokenNull()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "error_detail"
     */
    public function testPropertyErrorDetail()
    {
    }
}
