spring:
  application:
    name: sanjuan-api
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/expedientedb
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
bus-federal:
  access-token-url: https://auth-qa.bus-justicia.org.ar/auth/realms/bf-backend/protocol/openid-connect/token
  api-url: https://api-borde-qa.bus-justicia.org.ar
server:
  port: 8081
  servlet:
    context-path: /api
