spring:
  application:
    name: sanjuan-api
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
bus-federal:
  access-token-url: https://auth-qa.bus-justicia.org.ar/auth/realms/bf-backend/protocol/openid-connect/token
  api-url: https://api-borde-qa.bus-justicia.org.ar
server:
  port: 8081
  servlet:
    context-path: /api
